import { Link } from "@tanstack/react-router";
import { Menu, Phone, MapPin, MessageCircle, X, ChevronRight, Star, ShieldCheck } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { contact, navItems } from "@/lib/content";

export function Header(){const [open,setOpen]=useState(false);return <><header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur"><div className="bg-maroon text-primary-foreground"><div className="section-shell flex h-8 items-center justify-between text-xs"><span className="flex items-center gap-1.5"><MapPin className="size-3"/>Pachera, Aligarh</span><a href={`tel:${contact.phone}`} className="flex items-center gap-1.5 font-semibold"><Phone className="size-3"/>{contact.phone}</a></div></div><div className="section-shell flex h-18 items-center justify-between"><Link to="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full border-2 border-gold bg-maroon text-xl text-gold">ॐ</span><span><strong className="block font-display text-xl leading-none text-maroon">Astrologer Name</strong><small className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">Vedic Astrology</small></span></Link><nav className="hidden items-center gap-5 lg:flex">{navItems.map(([n,to])=><Link key={to} to={to} className="text-sm font-semibold text-foreground hover:text-saffron" activeProps={{className:"text-saffron"}}>{n}</Link>)}</nav><div className="hidden lg:block"><Button variant="hero" asChild><Link to="/contact">Book Consultation</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="section-shell grid gap-1 border-t border-border py-3 lg:hidden">{navItems.map(([n,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="rounded-md px-3 py-2 text-sm font-semibold hover:bg-muted">{n}</Link>)}</nav>}</header><a href={`https://wa.me/${contact.whatsapp}?text=${encodeURIComponent("Namaste, I would like to book an astrology consultation.")}`} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp" className="fixed bottom-5 right-5 z-50 grid size-14 place-items-center rounded-full bg-primary text-primary-foreground shadow-xl transition-transform hover:scale-105"><MessageCircle/></a></>}
export function Footer(){return <footer className="mt-20 bg-maroon text-primary-foreground"><div className="section-shell grid gap-10 py-14 md:grid-cols-4"><div><div className="mb-4 flex items-center gap-2 font-display text-2xl text-gold">ॐ Astrologer Name</div><p className="text-sm leading-6 opacity-80">Ethical Vedic guidance rooted in Lagna, Navamsa, Dasha and transits.</p></div><div><h3 className="mb-3 text-lg text-gold">Explore</h3><div className="grid gap-2 text-sm opacity-85"><Link to="/about">About</Link><Link to="/services">Services</Link><Link to="/free-kundli">Free Kundli</Link><Link to="/panchang">Aaj Ka Panchang</Link></div></div><div><h3 className="mb-3 text-lg text-gold">Guidance</h3><div className="grid gap-2 text-sm opacity-85"><Link to="/horoscope">Horoscope</Link><Link to="/kundli-matching">Kundli Milan</Link><Link to="/blog">Articles</Link><Link to="/faq">FAQ</Link></div></div><div><h3 className="mb-3 text-lg text-gold">Contact</h3><p className="text-sm leading-7 opacity-85">{contact.phone}<br/>{contact.address}</p><div className="mt-3 flex gap-3 text-xs"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/payment-info">Payments</Link></div></div></div><div className="border-t border-primary-foreground/15 py-5 text-center text-xs opacity-70">© {new Date().getFullYear()} Astrologer Name. Astrology offers guidance, not guaranteed outcomes.</div></footer>}
export function Breadcrumbs({items}:{items:string[]}){return <div className="section-shell flex items-center gap-2 py-5 text-xs text-muted-foreground"><Link to="/">Home</Link>{items.map(i=><span key={i} className="flex items-center gap-2"><ChevronRight className="size-3"/>{i}</span>)}</div>}
export function PageHero({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <div className="bg-maroon text-primary-foreground"><div className="section-shell py-16 md:py-24"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-gold">{eyebrow}</p><h1 className="max-w-4xl text-balance text-4xl font-semibold md:text-6xl">{title}</h1><div className="mt-5 max-w-2xl text-base leading-7 opacity-85">{children}</div></div></div>}
export function SectionHeading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="mx-auto mb-10 max-w-2xl text-center"><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-saffron">{eyebrow}</p><h2 className="text-balance text-3xl font-semibold text-maroon md:text-5xl">{title}</h2>{copy&&<p className="mt-4 leading-7 text-muted-foreground">{copy}</p>}</div>}
export function TrustStrip(){return <div className="border-y border-border bg-cream"><div className="section-shell grid grid-cols-2 gap-5 py-7 text-center md:grid-cols-4">{[["25+","Years of practice"],["18,000+","Kundlis analysed"],["D-9","Navamsa-led method"],["100%","Ethical guidance"]].map(([a,b])=><div key={b}><strong className="font-display text-3xl text-maroon">{a}</strong><span className="block text-xs text-muted-foreground">{b}</span></div>)}</div></div>}
export function Stars(){return <div className="flex gap-0.5 text-gold">{[1,2,3,4,5].map(i=><Star key={i} className="size-4 fill-current"/>)}</div>}
export function Disclaimer(){return <div className="flex gap-3 rounded-md border border-border bg-muted p-4 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-saffron"/>Astrological analysis is interpretive guidance. For medical, legal, or financial decisions, consult a qualified professional.</div>}
export function PageShellStyles(){return <style>{`.section-shell{width:100%;max-width:1200px;margin:0 auto;padding:0 1rem}`}</style>}