/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FreeKundliRouteImport } from './routes/free-kundli'
import { Route as KundliMatchingRouteImport } from './routes/kundli-matching'
import { Route as PanchangRouteImport } from './routes/panchang'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HoroscopeIndexRouteImport } from './routes/horoscope.index'
import { Route as HoroscopeRashiRouteImport } from './routes/horoscope.$rashi'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeKundliRoute = FreeKundliRouteImport.update({
  id: '/free-kundli',
  path: '/free-kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const KundliMatchingRoute = KundliMatchingRouteImport.update({
  id: '/kundli-matching',
  path: '/kundli-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangRoute = PanchangRouteImport.update({
  id: '/panchang',
  path: '/panchang',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeIndexRoute = HoroscopeIndexRouteImport.update({
  id: '/horoscope/',
  path: '/horoscope/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRashiRoute = HoroscopeRashiRouteImport.update({
  id: '/horoscope/$rashi',
  path: '/horoscope/$rashi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-kundli': typeof FreeKundliRoute
  '/kundli-matching': typeof KundliMatchingRoute
  '/panchang': typeof PanchangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/horoscope/$rashi': typeof HoroscopeRashiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-kundli': typeof FreeKundliRoute
  '/kundli-matching': typeof KundliMatchingRoute
  '/panchang': typeof PanchangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/horoscope/$rashi': typeof HoroscopeRashiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/horoscope': typeof HoroscopeIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free-kundli': typeof FreeKundliRoute
  '/kundli-matching': typeof KundliMatchingRoute
  '/panchang': typeof PanchangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/horoscope/$rashi': typeof HoroscopeRashiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/faq'
    | '/free-kundli'
    | '/kundli-matching'
    | '/panchang'
    | '/blog/$slug'
    | '/horoscope/$rashi'
    | '/services/$slug'
    | '/blog/'
    | '/horoscope/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/faq'
    | '/free-kundli'
    | '/kundli-matching'
    | '/panchang'
    | '/blog/$slug'
    | '/horoscope/$rashi'
    | '/services/$slug'
    | '/blog'
    | '/horoscope'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/faq'
    | '/free-kundli'
    | '/kundli-matching'
    | '/panchang'
    | '/blog/$slug'
    | '/horoscope/$rashi'
    | '/services/$slug'
    | '/blog/'
    | '/horoscope/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FreeKundliRoute: typeof FreeKundliRoute
  KundliMatchingRoute: typeof KundliMatchingRoute
  PanchangRoute: typeof PanchangRoute
  BlogSlugRoute: typeof BlogSlugRoute
  HoroscopeRashiRoute: typeof HoroscopeRashiRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HoroscopeIndexRoute: typeof HoroscopeIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-kundli': {
      id: '/free-kundli'
      path: '/free-kundli'
      fullPath: '/free-kundli'
      preLoaderRoute: typeof FreeKundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundli-matching': {
      id: '/kundli-matching'
      path: '/kundli-matching'
      fullPath: '/kundli-matching'
      preLoaderRoute: typeof KundliMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchang': {
      id: '/panchang'
      path: '/panchang'
      fullPath: '/panchang'
      preLoaderRoute: typeof PanchangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/': {
      id: '/horoscope/'
      path: '/horoscope'
      fullPath: '/horoscope/'
      preLoaderRoute: typeof HoroscopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/$rashi': {
      id: '/horoscope/$rashi'
      path: '/horoscope/$rashi'
      fullPath: '/horoscope/$rashi'
      preLoaderRoute: typeof HoroscopeRashiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FreeKundliRoute: FreeKundliRoute,
  KundliMatchingRoute: KundliMatchingRoute,
  PanchangRoute: PanchangRoute,
  BlogSlugRoute: BlogSlugRoute,
  HoroscopeRashiRoute: HoroscopeRashiRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  HoroscopeIndexRoute: HoroscopeIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
